// frontend/src/utils/constants.ts
import { PricingTier, ServiceProviderPricingTier } from '../types';

export const PRICING_TIERS: PricingTier[] = [
  {
    name: 'Basic Monthly',
    plan: 'Basic',
    price: '$20',
    assetLimit: 5,
    seatLimit: 1,
    features: [
      'Up to 5 assets',
      'AI-powered maintenance insights',
      'Maintenance tracking',
      'Task management',
      'FMEA',
      'RCA Tools',
      'Email notifications',
      'Maintenance schedule',
      '7-day free trial (credit card required)',
    ],
  },
  {
    name: 'Professional Monthly',
    plan: 'Professional',
    price: '$50',
    assetLimit: 'unlimited',
    seatLimit: 1,
    isPopular: true,
    features: [
      'Unlimited assets',
      'AI-powered maintenance insights',
      'Advanced reporting',
      'Team collaboration',
      'Priority support',
      'FMEA',
      'RCA Tools',
      'Email notifications',
      'Maintenance schedule',
      '7-day free trial (credit card required)',
    ],
  },
  {
    name: 'Annual',
    plan: 'Annual',
    price: '$449',
    assetLimit: 'unlimited',
    seatLimit: 1,
    features: [
      'Unlimited assets',
      'AI-powered maintenance insights',
      'Advanced reporting',
      'Team collaboration',
      'Priority support',
      'FMEA',
      'RCA Tools',
      'Email notifications',
      'Maintenance schedule',
      '7-day free trial (credit card required)',
    ],
  },
];

export const SERVICE_PROVIDER_PRICING_TIERS: ServiceProviderPricingTier[] = [
  {
    name: 'Verified',
    plan: 'verified',
    price: '$20',
    features: [
      'Service provider listing',
      'Verified badge on profile',
      'Enhanced credibility',
      'Basic profile information',
      'Contact through platform',
      'Priority in search results',
      'Customer reviews and ratings',
      'Email support',
    ],
  },
  {
    name: 'Premium',
    plan: 'premium',
    price: '$100',
    isPopular: true,
    features: [
      'Everything in Verified',
      'Direct messaging with customers',
      'Lead management tools',
      'Quote request notifications',
      'Advanced analytics',
      'Priority support',
    ],
  },
  {
    name: 'Promoted',
    plan: 'promoted',
    price: '$500',
    features: [
      'Everything in Premium',
      'Top placement in listings',
      'Featured provider badge',
      'Premium listing highlights',
      'Enhanced visibility',
      'Dedicated account manager',
      'Custom marketing support',
    ],
  },
];
